version: "3.3"
services:
  app:
    build: ./FlaskApp
    depends_on:
      - db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE_USER: ma
      MYSQL_DATABASE_PASSWORD: Ma123
      MYSQL_DATABASE_DB: BucketList
      MYSQL_DATABASE_HOST: db


  db:
    build: ./db
    ports:
      - "5002:5002"
    environment:
      MYSQL_ROOT_PASSWORD: Ma123
