---
- name: Jenkins
  hosts:  all
  gather_facts: false
  become: true
  vars_files:
    - ../vars.yml
  tasks:
    - name: Task Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: Task Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
          
    - name: ensure the jenkins apt repository key is installed
      apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
      become: yes

    - name: ensure the repository is configured
      apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
      become: yes

    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes
      become: yes

    - name: ensure jenkins is running
      service: name=jenkins state=started

    - name: Download and install Jenkins keyring
      ansible.builtin.shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null &&
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
    
    - name: Create initialization scripts directory
      file: path=/var/lib/jenkins/init.groovy.d
            state=directory
            owner=jenkins
            group=jenkins
            mode=0775

    - name: Add initialization script to setup basic security
      template: src=../security.groovy.j2
            dest=/var/lib/jenkins/init.groovy.d/security.groovy

    - name: Restart Jenkins
      service: name=jenkins state=restarted

    
        
    - name: "Turn off Jenkins setup wizard"
      lineinfile:
          dest: /etc/init.d/jenkins
          regexp: '^JAVA_ARGS='
          line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
          insertbefore: '^DAEMON_ARGS='

    - name: Restart Jenkins
      service: name=jenkins state=restarted
